version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: einvoice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: renbo123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_NAME=einvoice
      - DB_USER=postgres
      - DB_PASS=renbo123
      - DB_HOST=db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  postgres_data:
